@Entry
@Component
struct CaseDay02_2 {
  @State message: string = 'Hello World';

  build() {
    Column() {
      Row() {
        Flex() {
          Image('https://i0.hdslb.com/bfs/archive/b6480114f42a1fef29f74405df65003733af762e.jpg')
            .width(201)
            // .objectFit(ImageFit.Fill)
          Column() {
            Row() {
              Text('2024黑马程序员Java+AI智能辅助编程全套视频教程，java零基础入门到大牛一套通关')
                .fontSize(16)
                .fontColor('#212121')
                .textOverflow({ overflow: TextOverflow.Ellipsis })
                .maxLines(2)
            }
            Row({ space: 20 }) {
              Row({ space: 4 }) {
                Image('images/caseday02/2/play.svg')
                  .width(18.35)
                  .fillColor('#999')
                Text('15.3万')
                  .fontSize(12)
                  .fontColor('#999')
              }
              Row({ space: 4 }) {
                Image('images/caseday02/2/comment.svg')
                  .width(18.35)
                  .fillColor('#999')
                Text('1999')
                  .fontSize(12)
                  .fontColor('#999')
              }
            }
          }
          .margin({
            left: 10
          })
          .padding({
            top: 1,
            bottom: 2,
          })
          .justifyContent(FlexAlign.SpaceBetween)
          .alignItems(HorizontalAlign.Start)
          .height(71.34)
        }
      }
      .padding({
        top: 10.32,
        right: 13.76,
        bottom: 10.32,
        left: 10.32
      })
      // .height(84)
      .borderWidth({
        top: 0.8
      })
      .borderColor('#ccc')

      Row() {
        Flex() {
          Image('https://i1.hdslb.com/bfs/archive/58c3abb8243c6d040b309bc86eda794cac7027b2.jpg')
            .width(201)
          // .objectFit(ImageFit.Fill)
          Column() {
            Row() {
              Text('黑马程序员Java最新AI+若依框架项目开发新方案视频教程，基于RuoYi-Vue3前后端分离版本，从前端到后端再到AI智能化应用全通关')
                .fontSize(16)
                .fontColor('#212121')
                .textOverflow({ overflow: TextOverflow.Ellipsis })
                .maxLines(2)
            }
            Row({ space: 20 }) {
              Row({ space: 4 }) {
                Image('images/caseday02/2/play.svg')
                  .width(18.35)
                  .fillColor('#999')
                Text('15.3万')
                  .fontSize(12)
                  .fontColor('#999')
              }
              Row({ space: 4 }) {
                Image('images/caseday02/2/comment.svg')
                  .width(18.35)
                  .fillColor('#999')
                Text('1999')
                  .fontSize(12)
                  .fontColor('#999')
              }
            }
          }
          .margin({
            left: 10
          })
          .padding({
            top: 1,
            bottom: 2,
          })
          .justifyContent(FlexAlign.SpaceBetween)
          .alignItems(HorizontalAlign.Start)
          .height(71.34)
        }
      }
      .padding({
        top: 10.32,
        right: 13.76,
        bottom: 10.32,
        left: 10.32
      })
      // .height(84)
      .borderWidth({
        top: 0.8
      })
      .borderColor('#ccc')

      Row() {
        Flex() {
          Image('https://i0.hdslb.com/bfs/archive/74289b8c8c93006b01152ebae4169e526f91ff2c.jpg')
            .width(201)
          // .objectFit(ImageFit.Fill)
          Column() {
            Row() {
              Text('2024新版黑马程序员软件测试零基础入门到精通全套视频教程，包含Web测试、app手工测试，到AI测试提效，一套全通关')
                .fontSize(16)
                .fontColor('#212121')
                .textOverflow({ overflow: TextOverflow.Ellipsis })
                .maxLines(2)
            }
            Row({ space: 20 }) {
              Row({ space: 4 }) {
                Image('images/caseday02/2/play.svg')
                  .width(18.35)
                  .fillColor('#999')
                Text('15.3万')
                  .fontSize(12)
                  .fontColor('#999')
              }
              Row({ space: 4 }) {
                Image('images/caseday02/2/comment.svg')
                  .width(18.35)
                  .fillColor('#999')
                Text('1999')
                  .fontSize(12)
                  .fontColor('#999')
              }
            }
          }
          .margin({
            left: 10
          })
          .padding({
            top: 1,
            bottom: 2,
          })
          .justifyContent(FlexAlign.SpaceBetween)
          .alignItems(HorizontalAlign.Start)
          .height(71.34)
        }
      }
      .padding({
        top: 10.32,
        right: 13.76,
        bottom: 10.32,
        left: 10.32
      })
      // .height(84)
      .borderWidth({
        top: 0.8
      })
      .borderColor('#ccc')

      Row() {
        Flex() {
          Image('https://i0.hdslb.com/bfs/archive/3f309571b1989d114904558cddaf5abb55cfde3e.jpg')
            .width(201)
          // .objectFit(ImageFit.Fill)
          Column() {
            Row() {
              Text('2024新版黑马程序员C++零基础入门到精通全套视频教程，基于AI大模型的智能编码辅助编程，C++从基础到项目开发一套通关')
                .fontSize(16)
                .fontColor('#212121')
                .textOverflow({ overflow: TextOverflow.Ellipsis })
                .maxLines(2)
            }
            Row({ space: 20 }) {
              Row({ space: 4 }) {
                Image('images/caseday02/2/play.svg')
                  .width(18.35)
                  .fillColor('#999')
                Text('15.3万')
                  .fontSize(12)
                  .fontColor('#999')
              }
              Row({ space: 4 }) {
                Image('images/caseday02/2/comment.svg')
                  .width(18.35)
                  .fillColor('#999')
                Text('1999')
                  .fontSize(12)
                  .fontColor('#999')
              }
            }
          }
          .margin({
            left: 10
          })
          .padding({
            top: 1,
            bottom: 2,
          })
          .justifyContent(FlexAlign.SpaceBetween)
          .alignItems(HorizontalAlign.Start)
          .height(71.34)
        }
      }
      .padding({
        top: 10.32,
        right: 13.76,
        bottom: 10.32,
        left: 10.32
      })
      // .height(84)
      .borderWidth({
        top: 0.8
      })
      .borderColor('#ccc')
    }
    .width('100%')
    .height('100%')
  }
}